# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-elastic-beanstalk-application
  description: Terraform Module to define an ElasticBeanstalk Application
